defmodule Euler2 do
  @moduledoc """
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,…

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """

  def calc(n) do
    root5 = :math.sqrt(5)
    phi = (1 + root5) / 2

    1..33
    |> Enum.map(fn x -> trunc((phi ** (x * 3) + phi ** (-x * 3)) / (2 * phi - 1)) end)
    |> Enum.take_while(fn x -> x < n end)
    |> Enum.sum()
  end
end
